more release tests

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -9,13 +9,20 @@ on:
 
 env:
   RELEASE: dummy 
+  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
 
 jobs:
   Test-Job:
     timeout-minutes: 30
     runs-on: ubuntu-22.04
     steps:
-      - name: Make a release
+      - name: Get current date
+        run: echo "::set-output name=date::$(date +'%d%b%Y %H:%M:%S')"
+        id: date
+
+      - uses: actions/checkout@v3
+
+      - name: Create asset
         run: |
           touch asset.txt
           rand=$RANDOM
@@ -24,74 +31,83 @@ jobs:
             echo "blah $rand $i" >> asset.txt
             echo >> asset.txt
           done
-      - name: List Releases
-        id: list-releases
-        uses: github-actions-tools/gh-list-releases@main
 
-      - name: Check Release
-        id: release-check
+      - name: Release Info
+        id: release-info
         run: |
-          set +e
-          echo '${{ steps.list-releases.outputs.releases }}' | jq '.[]' | grep -q "$RELEASE"
-          has_release=$?
-          set -e
-          if [[ $has_release ]]; then
-            echo "::set-output name=hasrelease::yes"
-            echo "::set-output name=releasename::${RELEASE}-new"
-          else
-            echo "::set-output name=hasrelease::no"
-            echo "::set-output name=releasename::${RELEASE}"
-          fi
+          source .github/scripts/rfuncs.sh
+          echo "::set-output name=base-hasrelease::$(has_release ${RELEASE})"
+          echo "::set-output name=old-hasrelease::$(has_release ${RELEASE}-old)"
+          echo "::set-output name=new-hasrelease::$(has_release ${RELEASE}-new)"
 
-      - name: Old Check Release
-        id: old-release-check
+          echo "::set-output name=base-releaseid::$(get_release_id ${RELEASE})"
+          echo "::set-output name=old-releaseid::$(get_release_id ${RELEASE}-old)"
+          echo "::set-output name=new-releaseid::$(get_release_id ${RELEASE}-new)"
+
+
+      - name: Release Pre Checks
+        id: pre-release-check
         run: |
-          set +e
-          echo '${{ steps.list-releases.outputs.releases }}' | jq '.[]' | grep -q "${RELEASE}-old"
-          has_old_release=$?
-          set -e
-          if [[ $has_old_release && ${{ steps.release-check.outputs.hasrelease }} == "no" ]]; then
-            echo "ERROR: has an old release but no current release.. exiting"
-            exit 1
-          fi
+          echo "base-hasrelease: ${{ steps.release-info.outputs.base-hasrelease }}"
+          echo "old-hasrelease: ${{ steps.release-info.outputs.old-hasrelease }}"
+          echo "new-hasrelease: ${{ steps.release-info.outputs.new-hasrelease }}"
 
-      - name: Get current date
-        run: echo "::set-output name=date::$(date +'%d%b%Y %H:%M:%S')"
-        id: date
+          echo "base-releaseid: ${{ steps.release-info.outputs.base-releaseid }}"
+          echo "old-releaseid: ${{ steps.release-info.outputs.old-releaseid }}"
+          echo "new-releaseid: ${{ steps.release-info.outputs.new-releaseid }}"
+          #has_old_release=$?
+          #echo "has old release: $has_old_release"
+          #set -e
+          #if [[ $has_old_release && ${{ steps.release-check.outputs.hasrelease }} == "no" ]]; then
+          #  echo "ERROR: has an old release but no current release.. exiting"
+          #  exit 1
+          #fi
+          #export GH_TOKEN="${{ secrets.GITHUB_TOKEN }}"
+          #release_id=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/releases/tags/${RELEASE}-old | jq '.id')
+          #echo "::set-output name=releaseid::$release_id"
 
 
-      - name: Create Release
-        id: create-release
-        uses: softprops/action-gh-release@v1
-        with:
-          body: "New Body ${{ steps.date.outputs.date }}"
-          tag_name: "${{ steps.release-check.outputs.releasename }}"
-          name: "${{ steps.release-check.outputs.releasename }}"
-          files: asset.txt
+          #- name: Create Release
+          #  id: create-release
+          #  uses: softprops/action-gh-release@v1
+          #  with:
+          #    body: "New Body ${{ steps.date.outputs.date }}"
+          #    tag_name: "${{ steps.release-check.outputs.releasename }}"
+          #    name: "${{ steps.release-check.outputs.releasename }}"
+          #    files: asset.txt
 
-      - name: Get Release id
-        if: ${{ steps.release-check.outputs.has_release }} == "yes"
-        id: get-prev-id
-        run: |
-          export GH_TOKEN="${{ secrets.GITHUB_TOKEN }}"
-          release_id=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/releases/tags/${{ steps.release-check.outputs.releasename }} | jq '.id')
-          echo "rid: $release_id"
-          echo "::set-output name=releaseid::$release_id"
-      
-      - name: Rename old Release
-        if: ${{ steps.release-check.outputs.has_release }} == "yes"
-        uses: irongut/EditRelease@v1.2.0
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          id: ${{ steps.get-prev-id.outputs.releaseid }}
-          name: "${{ env.RELEASE }}-old"
-          replacename: true
+          #- name: Get Release id
+          #  if: ${{ steps.release-check.outputs.has_release }} == "yes"
+          #  id: get-new-id
+          #  run: |
+          #    export GH_TOKEN="${{ secrets.GITHUB_TOKEN }}"
+          #    release_id=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/releases/tags/${{ steps.release-check.outputs.releasename }} | jq '.id')
+          #    echo "rid: $release_id"
+          #    echo "::set-output name=releaseid::$release_id"
 
-      - name: Rename new Release
-        if: ${{ steps.release-check.outputs.has_release }} == "yes"
-        uses: irongut/EditRelease@v1.2.0
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          id: ${{ steps.create-release.outputs.id }}
-          name: "${{ env.RELEASE }}"
-          replacename: true
+          #- name: Get Old release id
+          #  if: ${{ steps.release-check.outputs.has_release }} == "yes"
+          #  id: get-old-id
+          #  run: |
+          #    export GH_TOKEN="${{ secrets.GITHUB_TOKEN }}"
+          #    release_id=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/releases/tags/${RELEASE} | jq '.id')
+          #    echo "old-rid: $release_id"
+          #    echo "::set-output name=releaseid::$release_id"
+          #
+          #- name: Rename old Release
+          #  if: ${{ steps.release-check.outputs.has_release }} == "yes"
+          #  uses: irongut/EditRelease@v1.2.0
+          #  with:
+          #    token: ${{ secrets.GITHUB_TOKEN }}
+          #    id: ${{ steps.get-prev-id.outputs.releaseid }}
+          #    name: "${{ env.RELEASE }}-old"
+          #    replacename: true
+
+          #- name: Rename new Release
+          #  if: ${{ steps.release-check.outputs.has_release }} == "yes"
+          #  uses: irongut/EditRelease@v1.2.0
+          #  with:
+          #    token: ${{ secrets.GITHUB_TOKEN }}
+          #    id: ${{ steps.create-release.outputs.id }}
+          #    name: "${{ env.RELEASE }}"
+          #    replacename: true
